image: mcr.microsoft.com/dotnet/sdk:8.0

stages:
  - restore
  - build
  - test

variables:
  DOTNET_CLI_TELEMETRY_OPTOUT: "1"
  DOTNET_NOLOGO: "1"

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .nuget/packages/

restore:
  stage: restore
  script:
    - dotnet restore

build:
  stage: build
  script:
    - dotnet build --no-restore --configuration Release

test:
  stage: test
  script:
    - dotnet test --no-build --configuration Release --collect:"XPlat Code Coverage"
  artifacts:
    when: always
    reports:
      junit: TestResults/**/*.xml
    paths:
      - TestResults/
      - coverage/
