image: mcr.microsoft.com/dotnet/sdk:8.0

stages:
  - build
  - test

variables:
  DOTNET_CLI_TELEMETRY_OPTOUT: 
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

before_script:
  - dotnet restore

build_job:
  stage: build
  script:
    - dotnet build --no-restore --configuration Release
  only:
    - main
    - master

test_job:
  stage: test
  script:
    - dotnet test --no-build --verbosity normal
  only:
    - main
    - master
